config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index'
  get    'tasks/new',      to: 'tasks#new', as: :tasks_new
  post   'tasks',          to: 'tasks#create'
  get    'tasks/:id',      to: 'tasks#show', as: :task

  get    'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch  'tasks/:id',      to: 'tasks#update'

  delete 'tasks/:id',      to: 'tasks#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit; end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit a Task</h1>

<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>

  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.check_box :completed %>

  <%= t.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<% @tasks.each do |task| %>
  <p>
    <%= if task.completed == true
      check_box_tag(task.title, task.title, checked = true, disabled: true)
        else
       check_box_tag(task.title, task.title, checked = false, disabled: true)
        end%>
       <%= link_to(task.title, task_path(task)) %>
   </p>
  <p><%= link_to "Delete", task_path(task),
      method: :delete,
      data: { confirm: "Are you sure?" } %></p>

<% end %>
<%= link_to('Add a new task', tasks_new_path) %>

app/views/tasks/new.html.erb
<h1>Create a Task</h1>

<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>

  <%= t.label :details %>
  <%= t.text_field :details %>

  <%= t.submit %>
<% end %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
  <p>
    Completed?
    <%= if @task.completed == true
      check_box_tag(@task.title, @task.title, checked = true, disabled: true)
        else
       check_box_tag(@task.title, @task.title, checked = false, disabled: true)
        end%>
  </p>


<!-- <p><%= @task.completed %></p> -->

<%= link_to('Edit this task', edit_task_path(@task)) %>
<%= link_to('View all tasks', tasks_path) %>